name: merge jobs

on:
  pull_request:
    branches: 
      - main
      - dev
      - qa
      - prod
    types: [opened, synchronize, reopened]

  workflow_dispatch:

env:
  VAR_BRANCH: ${{ github.ref_name }} 
  VAR_DEBUG_vars: ${{ toJson(vars) }}
    
jobs:
  # imprimir nombre y rama si la rama es dev
  job-dev:
    if: ${{ github.ref_name == 'dev' }}
     
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo
          echo "Tarea: imprimir nombre y rama si la rama es dev"
          echo "-------------------------------"
          echo "Datos de Salida Job: $GITHUB_JOB"
          echo "-------------------------------"
          echo "rama: $VAR_BRANCH"
          echo "nombre: ${{ vars.ALUMNO_REPO }}"
          echo "-------------------------------"
          echo "-        Debug vars...        -" 
          echo "vars: $VAR_DEBUG_vars"
          echo "-------------------------------"
          echo "-  Debug Enviroment vars...   -" 
          echo "nombre: ${{ vars.ALUMNO }}"

  # imprimir email y rama si la rama es qa
  job-qa:
    if: ${{ github.ref_name == 'qa' }}
      
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo
          echo "Tarea: imprimir email y rama si la rama es qa"
          echo "-------------------------------"
          echo "Datos de Salida Job: $GITHUB_JOB"
          echo "-------------------------------"
          echo "rama: $VAR_BRANCH"
          echo "email: ${{ vars.EMAIL_REPO }}"
          echo "-------------------------------"
          echo "-        Debug vars...        -" 
          echo "vars: $VAR_DEBUG_vars"
          echo "-------------------------------"
          echo "-  Debug Enviroment vars...   -" 
          echo "email: ${{ vars.EMAIL }}"

  # imprimir nombre y rama si la rama es prod
  job-prod:
    if: ${{ github.ref_name == 'prod' }}
          
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo
          echo "Tarea: imprimir nombre y rama si la rama es prod"
          echo "-------------------------------"
          echo "Datos de Salida Job: $GITHUB_JOB"
          echo "-------------------------------"
          echo "rama: $VAR_BRANCH"
          echo "nombre: ${{ vars.ALUMNO_REPO }}"
          echo "email: ${{ vars.EMAIL_REPO }}"
          echo "-------------------------------"
          echo "-        Debug vars...        -" 
          echo "vars: $VAR_DEBUG_vars"
          echo "-------------------------------"
          echo "-  Debug Enviroment vars...   -" 
          echo "nombre: ${{ vars.ALUMNO }}"
          echo "email: ${{ vars.EMAIL }}"

