name: merge jobs

on:
  pull_request:
    branches: 
      - qa
    types:
      - closed

  workflow_dispatch:

env:
  VAR_BRANCH: ${{ github.ref_name }} 
  VAR_DEBUG_vars: ${{ toJson(vars) }}
    
jobs:
  # imprimir email y rama si la rama es qa
  job-1-qa:
    if: github.event.pull_request.merged == true
      
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo
          echo "Tarea: imprimir email y rama si la rama es qa"
          echo "-------------------------------"
          echo "Datos de Salida Job: $GITHUB_JOB"
          echo "-------------------------------"
          echo "rama: $VAR_BRANCH"
          echo "email: ${{ vars.EMAIL_REPO }}"
          echo "-------------------------------"
          echo "-        Debug vars...        -" 
          echo "vars: $VAR_DEBUG_vars"
          echo "-------------------------------"
          echo "-  Debug Enviroment vars...   -" 
          echo "email: ${{ vars.EMAIL }}"
