name: merge job1 prod

on:
  pull_request:
    branches: 
      - main
      - prod
    types:
      - closed

  workflow_dispatch:

env:
  VAR_BRANCH: ${{ github.ref_name }} 
  VAR_DEBUG_vars: ${{ toJson(vars) }}
    
jobs:
  # imprimir nombre y rama si la rama es prod
  job-1-prod:
    if: github.event.pull_request.merged == true
          
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo
          echo "Tarea: imprimir nombre y rama si la rama es prod"
          echo "-------------------------------"
          echo "Datos de Salida Job: $GITHUB_JOB"
          echo "-------------------------------"
          echo "rama: $VAR_BRANCH"
          echo "nombre: ${{ vars.ALUMNO_REPO }}"
          echo "email: ${{ vars.EMAIL_REPO }}"
          echo "-------------------------------"
          echo "-        Debug vars...        -" 
          echo "vars: $VAR_DEBUG_vars"
          echo "-------------------------------"
          echo "-  Debug Enviroment vars...   -" 
          echo "nombre: ${{ vars.ALUMNO }}"
          echo "email: ${{ vars.EMAIL }}"

