name: mrg-jbs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - dev
    types: [opened, reopened, synchronize]

  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_REF_NAME: ${{ github.ref_name }} 
  MY_ENV_REF_NAME2: ${{ github.ref_name }} 
    
jobs:
  # imprimir nombre y rama si la rama es dev
  job-dev:
    if: ${{ github.ref_name == 'dev' }}
    
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Datos de Salida Job 1:"
          echo "rama: $MY_REF_NAME"
          echo "nombre: ${{ vars.ALUMNO }}"
          echo "nombre: ${{ vars.ALUMNOS }}"
          echo "nombre: $vars.ALUMNO"
          echo "nombre: $vars.ALUMNOS"

  # imprimir email y rama si la rama es qa
  job-qa:
    # if: ${{ github.ref_name == 'qa' }}
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Datos de Salida Job 1:"
          echo "rama: $MY_REF_NAME"
          echo "nombre: ${{ vars.ALUMNO }}"
          echo "nombre: ${{ vars.ALUMNOS }}"
          echo "nombre: $vars.ALUMNO"
          echo "nombre: $vars.ALUMNOS"

  # imprimir nombre y rama si la rama es prod
  job-prod:
    # if: ${{ github.ref_name == 'prod' }}
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 3
        run: |
          echo "Datos de Salida Job 1:"
          echo "rama: ${{ github.ref_name }}"
          echo ${{ vars.ALUMNO }}
          echo ${{ vars.ALUMNOS }}
          echo $vars.ALUMNO
          echo $vars.ALUMNOS


  # hacer curl a la URL e imprimir el resultado junto con el nombre de la rama
  job-2:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 4
        run: |
          echo "Datos de Salida Job 2:"
          echo "rama: ${{ github.ref_name }}"
          curl $secrets.URL


