name: mrg-jbs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
      - dev
      - qa
      - prod
    types: [opened, reopened, synchronize]

  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # imprimir nombre y rama si la rama es dev
  job-dev:
    if: $env_var1 == 'dev'
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 1
        run: |
          echo "rama: ${{ vars.ENV_CONTEXT_VAR }}"
          echo "nombre: ${{ vars.ALUMNO }}"

  # imprimir email y rama si la rama es qa
  job-qa:
    if: $env_var1 == 'qa'
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 2
        run: |
          echo "rama: ${{ vars.ENV_CONTEXT_VAR }}"
          echo "email: ${{ vars.EMAIL }}"

  # imprimir nombre y rama si la rama es prod
  job-prod:
    if: $env_var1 == 'prod'
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 3
        run: |
          echo "rama: ${{ vars.ENV_CONTEXT_VAR }}"
          echo "nombre: ${{ vars.ALUMNO }}"
          echo "email: ${{ vars.EMAIL }}"

  # hacer curl a la URL e imprimir el resultado junto con el nombre de la rama
  job-2:
    runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 4
        run: |
          echo "rama: ${{ vars.ENV_CONTEXT_VAR }}"
          curl ${{ secrets.URL }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script 4
        run: |
          echo "rama: $env_var1"
          curl ${{ secrets.URL }}


